const paths = require('../paths');
const del = require('del');
const gulp = require('gulp');
const replace = require('gulp-replace');
const rename = require('gulp-rename');
const shell = require('gulp-shell');

/**
 * WordPress Readme task
 */
module.exports = function wpReadme (callback) {
  return gulp.series(
    wpReadmeCreate,
    // wpReadmeCopy,
    // wpReadmeClean,
  )(callback);
}

/**
 * Create readme
 *
 * Parses the readme.txt file and outputs a `readme.md` in markdown using the
 * best generator.
 */
function wpReadmeCreate() {
  return gulp.src(paths.join(paths.ROOT, 'readme.txt'))
    .pipe(gulp.dest(paths.DIST))
    .pipe(shell([
      paths.join(paths.DEV_LIB, 'generators', './generate-markdown-readme')
    ], {
      cwd: paths.SRC
    }))
    .pipe(rename('README.md'))
    .pipe(gulp.dest(paths.DIST));
}

// /**
//  * Copy readme
//  *
//  * It copies the just autogenerated readme.md file to the dist folder renaming
//  * it to uppercase. This will be deployed to the dist branch `master` for
//  * readiblity on github or gitlab but it will later be removed from the
//  * distributable zip.
//  */
// function wpReadmeCopy() {
//   return gulp.src(paths.join(paths.DIST, 'readme.md'))
//     .pipe(rename('README.md'))
//     .pipe(gulp.dest(paths.DIST));
// }

// /**
//  * Clan readme
//  *
//  * It deletes the just autogenerated readme.md file from the root folder, over
//  * there we already have the README.md file which is the one targeting the
//  * `develop` branch.
//  */
// function wpReadmeClean() {
//   return del(paths.join(paths.ROOT, 'readme.md'), { force: true });
// }
